#Get the latest armv7 base image from
FROM resin/%%RESIN_MACHINE_NAME%%-python

MAINTAINER Shaun Mulligan <shaun@resin.io>

#switch on systemd init system in container
ENV INITSYSTEM on

# pip install python deps from requirements.txt
# For caching until requirements.txt changes
ADD ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY . /usr/src/app
WORKDIR /usr/src/app

#run main.py when the container starts
CMD ["python","/usr/src/app/src/main.py"]
